# Generated by Django 5.0.1 on 2024-11-24 16:46

import movies_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='uuid',
            field=models.UUIDField(default=movies_app.models.hex_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movies',
            name='uuid',
            field=models.UUIDField(default=movies_app.models.hex_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
